# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ga4gh/genotype_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ga4gh import variants_pb2 as ga4gh_dot_variants__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ga4gh/genotype_service.proto',
  package='ga4gh',
  syntax='proto3',
  serialized_pb=_b('\n\x1cga4gh/genotype_service.proto\x12\x05ga4gh\x1a\x14ga4gh/variants.proto\x1a\x1cgoogle/api/annotations.proto\"]\n\x0eGenotypeMatrix\x12\x14\n\x0cnindividuals\x18\x01 \x01(\r\x12\x11\n\tnvariants\x18\x02 \x01(\r\x12\"\n\tgenotypes\x18\x03 \x03(\x0e\x32\x0f.ga4gh.Genotype\"\xa1\x01\n\x16SearchGenotypesRequest\x12\x16\n\x0evariant_set_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61ll_set_ids\x18\x02 \x03(\t\x12\x16\n\x0ereference_name\x18\x03 \x01(\t\x12\r\n\x05start\x18\x04 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x03\x12\x11\n\tpage_size\x18\x06 \x01(\x05\x12\x12\n\npage_token\x18\x07 \x01(\t\"\x94\x01\n\x17SearchGenotypesResponse\x12 \n\x08variants\x18\x01 \x03(\x0b\x32\x0e.ga4gh.Variant\x12\x14\n\x0c\x63\x61ll_set_ids\x18\x02 \x03(\t\x12(\n\tgenotypes\x18\x03 \x01(\x0b\x32\x15.ga4gh.GenotypeMatrix\x12\x17\n\x0fnext_page_token\x18\x04 \x01(\t*\x83\x01\n\x08Genotype\x12\x12\n\x0eHOMOZYGOUS_REF\x10\x00\x12\x14\n\x10HETEROZYGOUS_ALT\x10\x01\x12\x12\n\x0eHOMOZYGOUS_ALT\x10\x02\x12\x12\n\x0eHEMIZYGOUS_REF\x10\x03\x12\x12\n\x0eHEMIZYGOUS_ALT\x10\x04\x12\t\n\x05OTHER\x10\x05\x12\x06\n\x02NA\x10\x06\x32\x8c\x01\n\x10GenotypesService\x12x\n\x0fSearchGenotypes\x12\x1d.ga4gh.SearchGenotypesRequest\x1a\x1e.ga4gh.SearchGenotypesResponse\"&\x82\xd3\xe4\x93\x02 \"\x1b/v0.6.0a10/genotypes/search:\x01*b\x06proto3')
  ,
  dependencies=[ga4gh_dot_variants__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GENOTYPE = _descriptor.EnumDescriptor(
  name='Genotype',
  full_name='ga4gh.Genotype',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOMOZYGOUS_REF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HETEROZYGOUS_ALT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOMOZYGOUS_ALT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEMIZYGOUS_REF', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEMIZYGOUS_ALT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NA', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=502,
  serialized_end=633,
)
_sym_db.RegisterEnumDescriptor(_GENOTYPE)

Genotype = enum_type_wrapper.EnumTypeWrapper(_GENOTYPE)
HOMOZYGOUS_REF = 0
HETEROZYGOUS_ALT = 1
HOMOZYGOUS_ALT = 2
HEMIZYGOUS_REF = 3
HEMIZYGOUS_ALT = 4
OTHER = 5
NA = 6



_GENOTYPEMATRIX = _descriptor.Descriptor(
  name='GenotypeMatrix',
  full_name='ga4gh.GenotypeMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nindividuals', full_name='ga4gh.GenotypeMatrix.nindividuals', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nvariants', full_name='ga4gh.GenotypeMatrix.nvariants', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genotypes', full_name='ga4gh.GenotypeMatrix.genotypes', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=184,
)


_SEARCHGENOTYPESREQUEST = _descriptor.Descriptor(
  name='SearchGenotypesRequest',
  full_name='ga4gh.SearchGenotypesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_set_id', full_name='ga4gh.SearchGenotypesRequest.variant_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='call_set_ids', full_name='ga4gh.SearchGenotypesRequest.call_set_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_name', full_name='ga4gh.SearchGenotypesRequest.reference_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ga4gh.SearchGenotypesRequest.start', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='ga4gh.SearchGenotypesRequest.end', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ga4gh.SearchGenotypesRequest.page_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ga4gh.SearchGenotypesRequest.page_token', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=348,
)


_SEARCHGENOTYPESRESPONSE = _descriptor.Descriptor(
  name='SearchGenotypesResponse',
  full_name='ga4gh.SearchGenotypesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variants', full_name='ga4gh.SearchGenotypesResponse.variants', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='call_set_ids', full_name='ga4gh.SearchGenotypesResponse.call_set_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genotypes', full_name='ga4gh.SearchGenotypesResponse.genotypes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='ga4gh.SearchGenotypesResponse.next_page_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=499,
)

_GENOTYPEMATRIX.fields_by_name['genotypes'].enum_type = _GENOTYPE
_SEARCHGENOTYPESRESPONSE.fields_by_name['variants'].message_type = ga4gh_dot_variants__pb2._VARIANT
_SEARCHGENOTYPESRESPONSE.fields_by_name['genotypes'].message_type = _GENOTYPEMATRIX
DESCRIPTOR.message_types_by_name['GenotypeMatrix'] = _GENOTYPEMATRIX
DESCRIPTOR.message_types_by_name['SearchGenotypesRequest'] = _SEARCHGENOTYPESREQUEST
DESCRIPTOR.message_types_by_name['SearchGenotypesResponse'] = _SEARCHGENOTYPESRESPONSE
DESCRIPTOR.enum_types_by_name['Genotype'] = _GENOTYPE

GenotypeMatrix = _reflection.GeneratedProtocolMessageType('GenotypeMatrix', (_message.Message,), dict(
  DESCRIPTOR = _GENOTYPEMATRIX,
  __module__ = 'ga4gh.genotype_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.GenotypeMatrix)
  ))
_sym_db.RegisterMessage(GenotypeMatrix)

SearchGenotypesRequest = _reflection.GeneratedProtocolMessageType('SearchGenotypesRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHGENOTYPESREQUEST,
  __module__ = 'ga4gh.genotype_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchGenotypesRequest)
  ))
_sym_db.RegisterMessage(SearchGenotypesRequest)

SearchGenotypesResponse = _reflection.GeneratedProtocolMessageType('SearchGenotypesResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHGENOTYPESRESPONSE,
  __module__ = 'ga4gh.genotype_service_pb2'
  # @@protoc_insertion_point(class_scope:ga4gh.SearchGenotypesResponse)
  ))
_sym_db.RegisterMessage(SearchGenotypesResponse)


# @@protoc_insertion_point(module_scope)
